---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "The S Gamejam 2022"
keywords:    "Gamejam, the s, epic"
description: "Welcome to the S gamejam 2022!"
source_link: "https://www.thesgamejam.org"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  saturday-one: '#66b266'
  monday:       '#5ea06e'
  tuesday:      '#578e77'
  wednesday:    '#4f7c80'
  thursday:     '#486a89'
  friday:       '#415992'
  saturday-two: '#39479b'

kramdown:
  auto_ids:  false

